name: Sample Workflow

on: push

jobs:
    first_job:
        name: First Job
        runs-on: ubuntu-22.04
        steps:
        - name: Checkout Repo  
          uses: actions/checkout@v4
 
        - name: Welcome message
          run: echo "Github Actions Job Its Working"

        - name: List File
          run: ls -lha

        - name: Read File
          run: cat README.md

        - name: Get Multiple Info Related to System
          run: |
            pwd
            lsb_release -a
            whoami
            cat /etc/os-release
            echo "ps aux to get process list"
            ps aux

        - name: executing Shell Script
          run: |
            chmod +x ./kodekloud-exercise/ascii-script.sh
            ./kodekloud-exercise/ascii-script.sh

        - name: check dragon file
          run: |
            pwd
            ls -lha ./kodekloud-exercise
            ls ./
            cat dragon.txt

        - uses: actions/upload-artifact@v4
          with:
            name: dragon-file
            path: dragon.txt

    second_job:
        needs: first_job
        name: Second Job
        runs-on: ubuntu-latest
        steps:
          - name: Sleep for 10 seconds
            run: sleep 10
          - name: Touch FIle
            run: |
              touch dragon.txt
              echo "dragons does not exists" >> dragon.txt
          - name: Grep File
            run: grep -i "dragon" dragon.txt

    third_job:
      needs: second_job
      name: Third Job
      runs-on: ubuntu-latest
      steps:
        - name: Sleep for 10 seconds
          run: sleep 10
        - uses: actions/download-artifact@v4
          with:
            name: dragon-file
        - name: Grep File
          run: grep -i "dragon" dragon.txt
    

