name: Generate ASCII Artwork

on:
    push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Generate ASCII Artwork - Execute Cowsay CMD
          run: cowsay -f dragon "Run for cover, I'm a DRAGON... RAWR" >> dragon.txt

        - name: Test File Exists
          run: grep -i "dragon" dragon.txt

        - name: Read File
          run: cat dragon.txt

        - name: Check repo file
          run: ls -lhatr
