name: Exploring Variables and Secrets
on:
    push


env: #defining variables in WORKFLOW level
  DOCKER_PASSWORD: test
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      env: #defining variables in STEP level
        CONTAINER_REGISTRY: test
        DOCKER_USERNAME: test
        IMAGE_NAME: test
      run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest
    - name: Docker Login #from WORKFLOW level
      run: echo docker login --username= --password=$DOCKER_PASSWORD
    - name: Docker Publish
      run: echo docker push 

  deploy:
    needs: docker
    env: #defining variables in JOB level
      IMAGE: test
    runs-on: ubuntu-latest
    steps:
    - name: Docker Login #from WORKFLOW level
      run: echo docker login --username= --password=${{ env.DOCKER_PASSWORD }} 
    - name: Pull Image
      run: echo pull $IMAGE
    - name: Run Image
      run: echo run $IMAGE

  notify:
    needs: deploy
    env: #defining variables in JOB level
      IMAGE: test
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Message
        run: echo $IMAGE was deployed
      - name: Send Email Message
        run: echo $IMAGE was deployed

    
